### ISSUE TITLE
Split Option Generates Incorrect Audio

### ISSUE THREAD

**Issue by mazz** [appurist/say2file#10]
Using eleven labs with my free account.

Issue:

When generating audio from a file, the correct number of audio files are generated but each file is generated audio from the LAST line of the file only.

Expected:

A different audio file generated for each line of the file.

Actual:

The same audio file generated for each line of the file.

Steps:

Command line:

```
node say2file -s -w oM72HLupvBwZ8PKFrUZd -f file2-copy.txt # oM72HLupvBwZ8PKFrUZd is Knightley
```

File contents(file2-copy.txt):

```
This is line one.
This is line two.
```

Two audio files are generated both with the audio "This is line two."

But there should actually be two audio files generated one saying "This is line one." and "This is line two."

using nodejs 18.16.1 on an M1 Mac(via asdf).

**Comment by appurist** [comment]
For the record, I can confirm the problem, and it also happens with my 5-audio line `sample.txt` file, where all 5 output files repeat the last line. I'll debug this, it's probably something simple.

**Comment by appurist** [comment]
This should be fixed in the update I just posted, a new version [2.2.202130](https://github.com/appurist/say2file/releases/tag/v2.2.202130).

Thanks @mazz for this report!

**Comment by mazz** [comment]
Glad to help!
